# Generated by Django 4.1.3 on 2022-11-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="time_minutes",
            field=models.IntegerField(),
        ),
    ]
