# Generated by Django 4.1.3 on 2022-11-30 04:36

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_ingredient_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                null=True, upload_to=recipe.models.recipe_image_file_path
            ),
        ),
    ]
